[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-payment"
  to = "/.netlify/functions/create-payment"
  status = 200
  force = true

[[redirects]]
  from = "/api/ipn"
  to = "/.netlify/functions/ipn"
  status = 200
  force = true
