// server.js
// Main Express application for Student Payment Verification System

require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const axios = require('axios');
const path = require('path');
const { db } = require('./firebase/firebase-config');

const app = express();
const PORT = process.env.PORT || 3000;

// ─── Middleware ───────────────────────────────────────────────────────────────
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// ─── Temporary in-memory store for pending payments ──────────────────────────
// Key: invoice_id (generated by us), Value: { name, roll, amount, department }
const pendingPayments = new Map();

// ─── Helper: Generate unique invoice ID ──────────────────────────────────────
function generateInvoiceId() {
  return 'INV-' + Date.now() + '-' + Math.random().toString(36).substr(2, 6).toUpperCase();
}

// ─── Routes ──────────────────────────────────────────────────────────────────

// Home page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Checkout page
app.get('/checkout', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'checkout.html'));
});

// Admin login page
app.get('/admin', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'admin', 'login.html'));
});

// Admin dashboard page
app.get('/admin/dashboard', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'admin', 'dashboard.html'));
});

// ─── POST /create-payment ─────────────────────────────────────────────────────
// Receives student data, creates a payment with UddoktaPay, returns payment_url
app.post('/create-payment', async (req, res) => {
  const { name, roll, amount, department } = req.body;

  // Basic validation
  if (!name || !roll || !amount || !department) {
    return res.status(400).json({ error: 'All fields are required.' });
  }

  // Generate a unique invoice ID for this transaction
  const invoiceId = generateInvoiceId();

  // Store student data temporarily (will be retrieved on success callback)
  pendingPayments.set(invoiceId, {
    name,
    roll,
    amount: parseFloat(amount),
    department,
  });

  // Auto-clean after 30 minutes to prevent memory leak
  setTimeout(() => pendingPayments.delete(invoiceId), 30 * 60 * 1000);

  try {
    // Call UddoktaPay Checkout API
    const response = await axios.post(
      `${process.env.UDDOKTAPAY_BASE_URL}/checkout`,
      {
        full_name: name,
        email: `${roll.toLowerCase()}@student.edu`, // placeholder email
        amount: parseFloat(amount),
        metadata: {
          invoice_id: invoiceId,
          roll: roll,
          department: department,
        },
        success_url: `${process.env.BASE_URL}/payment/success`,
        cancel_url: `${process.env.BASE_URL}/payment/cancel`,
      },
      {
        headers: {
          'RT-UDDOKTAPAY-API-KEY': process.env.UDDOKTAPAY_API_KEY,
          'Content-Type': 'application/json',
        },
      }
    );

    const { payment_url } = response.data;

    if (!payment_url) {
      throw new Error('No payment_url returned from UddoktaPay');
    }

    // Return payment URL to frontend
    return res.json({ payment_url, invoice_id: invoiceId });
  } catch (err) {
    console.error('❌ UddoktaPay Error:', err.response?.data || err.message);
    return res.status(500).json({
      error: 'Payment initiation failed. Please try again.',
      details: err.response?.data || err.message,
    });
  }
});

// ─── GET /payment/success ─────────────────────────────────────────────────────
// UddoktaPay redirects here after payment. Verify and store in Firebase.
app.get('/payment/success', async (req, res) => {
  const { invoice_id, trx_id, payment_id } = req.query;

  if (!invoice_id) {
    return res.redirect('/cancel.html?reason=missing_invoice');
  }

  try {
    // Verify payment with UddoktaPay
    const verifyResponse = await axios.post(
      `${process.env.UDDOKTAPAY_BASE_URL}/verify-payment`,
      { invoice_id },
      {
        headers: {
          'RT-UDDOKTAPAY-API-KEY': process.env.UDDOKTAPAY_API_KEY,
          'Content-Type': 'application/json',
        },
      }
    );

    const paymentData = verifyResponse.data;

    // Check if payment is verified/completed
    if (paymentData.status !== 'COMPLETED') {
      console.warn('⚠️ Payment not completed:', paymentData);
      return res.redirect('/cancel.html?reason=not_completed');
    }

    // Retrieve student data from temporary store
    const studentData = pendingPayments.get(invoice_id);

    if (!studentData) {
      // Data expired or not found — still show success with available data
      console.warn('⚠️ Student data not found for invoice:', invoice_id);
    }

    const record = {
      name: studentData?.name || paymentData.full_name || 'Unknown',
      roll: studentData?.roll || 'Unknown',
      amount: studentData?.amount || paymentData.amount,
      department: studentData?.department || 'Unknown',
      trxId: paymentData.trx_id || trx_id || '',
      paymentId: paymentData.payment_id || payment_id || invoice_id,
      invoiceId: invoice_id,
      timestamp: new Date().toISOString(),
      status: 'COMPLETED',
    };

    // Store in Firebase Realtime Database under /payments/{invoiceId}
    await db.ref(`payments/${invoice_id.replace(/[.#$[\]]/g, '_')}`).set(record);

    // Clean up temporary store
    pendingPayments.delete(invoice_id);

    console.log('✅ Payment stored:', record);

    // Redirect to success page with query params for display
    const params = new URLSearchParams({
      trxId: record.trxId,
      amount: record.amount,
      name: record.name,
      roll: record.roll,
      department: record.department,
    });

    return res.redirect(`/success.html?${params.toString()}`);
  } catch (err) {
    console.error('❌ Verification Error:', err.response?.data || err.message);
    return res.redirect('/cancel.html?reason=verification_failed');
  }
});

// ─── GET /payment/cancel ──────────────────────────────────────────────────────
app.get('/payment/cancel', (req, res) => {
  res.redirect('/cancel.html');
});

// ─── Start Server ─────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
});
